In [1]:
import pandas as pd

In [2]:
# There are some NaN rows in the data, which are dropped.
pv_meters = pd.read_excel("../../data/Liste_PV_available.xlsx").dropna(how="all")

In [6]:
# Renaming columns to conform to data model.
pv_meters["utility"] = pv_meters["Utility"]
pv_meters["municipality"] = pv_meters["Ort"]
pv_meters["address"] = pv_meters["Adress"]

pv_meters["installed_capacity_kw"] = pv_meters["installed capacity"]
pv_meters["orientation_deg"] = pv_meters["orientation 1"]
pv_meters["slope_deg"] = pv_meters["slope"]

# Resetting index because we will use it as a unique identifier.
pv_meters.reset_index(inplace=True)
pv_meters["id"] = pv_meters.index

In [7]:
data_clean = pv_meters[
    [
        "id",
        "lat",
        "lon",
        "address",
        "municipality",
        "utility",
        "installed_capacity_kw",
        "slope_deg",
        "orientation_deg",
    ]
]

In [8]:
data_clean

,id,lat,lon,address,municipality,utility,installed_capacity_kw,slope_deg,orientation_deg
0,0,47.359609,8.726619,Hallenbadweg 3,Uster,Energieuster,452.98,15.0,118.0
1,1,47.354941,8.263447,Wilstrasse 71,Wohlen,IBW,430.63,0.0,0.0
2,2,47.351690,8.292134,Schweikhof,Wohlen,IBW,122.85,25.0,52.0
3,3,47.134577,8.581721,Buchholzstrasse 19,Unter채geri,WWZ,70.00,10.0,256.0
4,4,46.930736,7.119635,L채ngmatt 6,Murten,IBM,30.00,17.0,138.0
5,5,46.930022,7.126763,Herrenschwandweg 2,Murten,IBM,113.00,0.0,0.0
6,6,47.142452,7.278259,Orpundstrasse 60,Biel,ESB,58.00,10.0,290.0
7,7,47.040772,9.067346,Zweiggartenturnhalle,Glarus,TBG,67.00,10.0,205.0
8,8,46.782773,6.642840,Rue de l'Ancien Stand 2,Yverdon,NaN,28.00,8.0,299.0

In [9]:
data_clean.to_pickle("../../data/pv_meters.pkl")